alias PhoenixRaffley.Repo
alias PhoenixRaffley.Raffles
alias PhoenixRaffley.RaffleAdmin
alias PhoenixRaffley.Raffles.Raffle
alias PhoenixRaffley.Charities.Charity
alias PhoenixRaffley.Accounts.User
alias PhoenixRaffley.Tickets.Ticket
import Ecto.Query
import Ecto.Changeset
